model_configuration_1:
  model_type: 'LogisticRegression'
  params:
    penalty: 'l2'
    dual: False
    tol: 0.0001
    C: 1.0
    fit_intercept: True
    intercept_scaling: 1
    class_weight: null
    solver: 'lbfgs'
    max_iter: 100
    verbose: 0
    warm_start: False
    n_jobs: null
    l1_ratio: null

model_configuration_2:
  model_type: 'RandomForestClassifier'
  params:
    n_estimators: 100
    criterion: 'gini'
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: 'sqrt'
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: True
    oob_score: False
    n_jobs: null
    random_state: null
    verbose: 0
    warm_start: False
    class_weight: null
    ccp_alpha: 0.0
    max_samples: null

model_configuration_3:
  model_type: "SVC"
  params:
    C: 1.0
    kernel: 'rbf'
    degree: 3
    gamma: 'scale'
    coef0: 0.0
    shrinking: True
    probability: False
    tol: 0.001
    cache_size: 200
    class_weight: null
    verbose: False
    max_iter: -1
    decision_function_shape: 'ovr'
    break_ties: False
    random_state: null

model_configuration_4:
  model_type: "BalancedRandomForestClassifier"
  params:
    n_estimators: 100
    criterion: "gini"
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: "sqrt"
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: false
    oob_score: false
    sampling_strategy: "majority"
    replacement: true
    n_jobs: null
    random_state: null
    verbose: 0
    warm_start: false
    class_weight: null
    ccp_alpha: 0.0
    max_samples: null
    monotonic_cst: null

model_configuration_5:
  model_type: 'RandomForestClassifier'
  params:
    n_estimators: 300
    criterion: 'gini'
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: 'sqrt'
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: True
    oob_score: False
    n_jobs: null
    random_state: null
    verbose: 0
    warm_start: False
    class_weight: null
    ccp_alpha: 0.0
    max_samples: null

    
model_configuration_6:
  model_type: 'GradientBoostingClassifier'
  params:
    loss: "log_loss"
    learning_rate: 0.1
    n_estimators: 100
    subsample: 1.0
    criterion: "friedman_mse"
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_depth: 3
    min_impurity_decrease: 0.0
    init: null
    random_state: null
    max_features: null
    verbose: 0
    max_leaf_nodes: null
    warm_start: false
    validation_fraction: 0.1
    n_iter_no_change: null
    tol: 0.0001
    ccp_alpha: 0.0


model_configuration_7:
  model_type: 'RandomForestClassifier'
  params:
    n_estimators: 20
    criterion: 'gini'
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: 'sqrt'
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: True
    oob_score: False
    n_jobs: null
    random_state: null
    verbose: 0
    warm_start: False
    class_weight: null
    ccp_alpha: 0.0
    max_samples: null

model_configuration_8:
  model_type: 'KNeighborsClassifier'
  params:
    n_neighbors: 5
    weights: 'uniform'
    algorithm: 'auto'
    leaf_size: 30
    p: 2
    metric: 'minkowski'
    metric_params: null
    n_jobs: null
